spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/restapi?currentSchema=data
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

springdoc:
  paths-to-match: /api/v1/**
  swagger-ui:
    use-root-path: true